"""Spectral estimation against signals whose spectrum is known by construction."""

from __future__ import annotations

import numpy as np
import pytest

from polarmed.config import load_config
from polarmed.metrics.frequency import (
    band_power,
    parabolic_peak,
    resample_uniform,
    spectrum,
    summarise,
)


@pytest.fixture(scope="module")
def spectral_config():
    return load_config().spectral


def synthetic_tachogram(freq_hz: float, amplitude_ms: float = 60.0,
                        duration_s: float = 900.0, mean_rr: float = 800.0):
    """An RR series modulated by one sinusoid at a known frequency.

    Beat times are generated by accumulating the intervals, so the series is
    irregularly sampled exactly as a real tachogram is.
    """
    times, values, clock = [], [], 0.0
    while clock < duration_s:
        rr = mean_rr + amplitude_ms * np.sin(2 * np.pi * freq_hz * clock)
        times.append(clock)
        values.append(rr)
        clock += rr / 1000.0
    return np.asarray(values), np.asarray(times)


class TestPeakRecovery:
    @pytest.mark.parametrize("freq", [0.062, 0.103, 0.151, 0.247])
    def test_recovers_the_driving_frequency(self, freq, spectral_config):
        """Sub-bin accuracy: bin spacing alone would give ~0.0167 Hz steps."""
        rr, t = synthetic_tachogram(freq)
        result = summarise(rr, t, spectral_config)
        assert result["peak_freq_hz"] == pytest.approx(freq, abs=0.004)

    def test_slow_chanting_rhythm_is_read_accurately(self, spectral_config):
        """0.1 Hz is the rhythm the whole report turns on."""
        rr, t = synthetic_tachogram(0.1)
        freqs, psd, _ = spectrum(rr, t, spectral_config)
        peak = parabolic_peak(freqs, psd, 0.04, 0.40)
        assert peak == pytest.approx(0.1, abs=0.002)

    def test_parabolic_interpolation_beats_raw_bin_picking(self, spectral_config):
        """The reason for nfft padding plus interpolation (PLAN.md 4.3b)."""
        target = 0.1055  # deliberately between bins
        rr, t = synthetic_tachogram(target)
        freqs, psd, _ = spectrum(rr, t, spectral_config)
        raw_bin = freqs[(freqs >= 0.04) & (freqs <= 0.40)][
            np.argmax(psd[(freqs >= 0.04) & (freqs <= 0.40)])
        ]
        interpolated = parabolic_peak(freqs, psd, 0.04, 0.40)
        assert abs(interpolated - target) <= abs(raw_bin - target) + 1e-9


class TestBandPower:
    def test_power_lands_in_the_band_containing_the_driver(self, spectral_config):
        rr, t = synthetic_tachogram(0.08)  # inside SLOW (0.05-0.12)
        result = summarise(rr, t, spectral_config)
        assert result["SLOW_abs"] > result["HF_abs"]
        assert result["SLOW_rel"] > 0.5

    def test_fast_breathing_puts_power_in_hf(self, spectral_config):
        rr, t = synthetic_tachogram(0.28)  # inside HF (0.15-0.40)
        result = summarise(rr, t, spectral_config)
        assert result["HF_abs"] > result["SLOW_abs"]

    def test_the_slow_over_hf_ratio_separates_the_two_cases(self, spectral_config):
        """The report's headline statistic must respond to the right thing."""
        slow_rr, slow_t = synthetic_tachogram(0.08)
        fast_rr, fast_t = synthetic_tachogram(0.28)
        slow = summarise(slow_rr, slow_t, spectral_config)
        fast = summarise(fast_rr, fast_t, spectral_config)
        slow_ratio = np.log10(slow["SLOW_abs"] / slow["HF_abs"])
        fast_ratio = np.log10(fast["SLOW_abs"] / fast["HF_abs"])
        assert slow_ratio > 1.0
        assert fast_ratio < 0.0

    def test_empty_band_is_nan_not_zero(self):
        freqs = np.linspace(0.0, 0.5, 100)
        psd = np.ones_like(freqs)
        assert np.isnan(band_power(freqs, psd, 0.9, 1.0))


class TestConcentration:
    def test_a_pure_tone_is_highly_concentrated(self, spectral_config):
        rr, t = synthetic_tachogram(0.1, amplitude_ms=80.0)
        assert summarise(rr, t, spectral_config)["spectral_concentration"] > 0.7

    def test_broadband_noise_is_not(self, spectral_config):
        rng = np.random.default_rng(11)
        rr = 800.0 + rng.normal(0, 40, 1100)
        t = np.cumsum(rr) / 1000.0
        result = summarise(rr, t, spectral_config)
        assert result["spectral_concentration"] < 0.4


class TestResampling:
    def test_produces_a_uniform_grid_at_the_requested_rate(self):
        rr, t = synthetic_tachogram(0.1, duration_s=120.0)
        grid, values = resample_uniform(rr, t, 4.0)
        assert grid.size == values.size
        assert np.allclose(np.diff(grid), 0.25, atol=1e-9)

    def test_too_short_a_series_returns_empty(self):
        grid, values = resample_uniform(np.array([800.0, 810.0]), np.array([0.0, 0.8]), 4.0)
        assert grid.size == 0 and values.size == 0


class TestDegradation:
    def test_short_segment_degrades_instead_of_raising(self, spectral_config):
        """A 16 s window must not abort the run, and must say it is thin.

        It still returns numbers, but with too few Welch segments to average -
        which is precisely what ``reliability.min_welch_segments`` then uses to
        mark the row unreliable rather than presenting it as sound.
        """
        rr = np.full(20, 800.0)
        t = np.cumsum(rr) / 1000.0
        result = summarise(rr, t, spectral_config)
        assert result["n_welch_segments"] < 2

    def test_a_constant_series_has_no_spectral_power(self, spectral_config):
        rr = np.full(400, 800.0)
        t = np.cumsum(rr) / 1000.0
        result = summarise(rr, t, spectral_config)
        assert result["total_power"] == pytest.approx(0.0, abs=1e-6)

    def test_window_length_is_reported_with_every_row(self, spectral_config):
        """Without it, nobody can tell what two spectra are being compared."""
        rr, t = synthetic_tachogram(0.1)
        result = summarise(rr, t, spectral_config)
        assert result["welch_window_s"] == spectral_config.window_s
        assert result["n_welch_segments"] >= 2
